In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

student_features_first_25 = pd.read_csv("data/processed/student_features_first_25.csv"
)
student_features_first_25

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,subpage,url,avg_score_until_cutoff,min_score_until_cutoff,max_score_until_cutoff,submitted_assessments_until_cutoff,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,23.0,1.0,81.5,78.0,85.0,2.0,0.0,-1.0,2.00,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,62.0,33.0,69.0,68.0,70.0,2.0,1.0,0.5,0.50,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,22.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,78.0,39.0,71.5,71.0,72.0,2.0,0.0,-2.5,0.50,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,29.0,6.0,69.0,69.0,69.0,1.0,1.0,7.0,0.50,light
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32475,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,...,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25,light
32476,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25,light
32477,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,...,13.0,0.0,65.0,65.0,65.0,1.0,0.0,-11.0,0.25,light
32478,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,...,10.0,0.0,83.0,83.0,83.0,1.0,0.0,-5.0,0.25,light
32479,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,...,23.0,0.0,80.0,80.0,80.0,1.0,0.0,-24.0,0.25,light

In [2]:
df_25 = student_features_first_25.copy()

print(df_25.shape)

df_25.head()

(32480, 46)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,subpage,url,avg_score_until_cutoff,min_score_until_cutoff,max_score_until_cutoff,submitted_assessments_until_cutoff,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,23.0,1.0,81.5,78.0,85.0,2.0,0.0,-1.0,2.0,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,62.0,33.0,69.0,68.0,70.0,2.0,1.0,0.5,0.5,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,22.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,78.0,39.0,71.5,71.0,72.0,2.0,0.0,-2.5,0.5,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,29.0,6.0,69.0,69.0,69.0,1.0,1.0,7.0,0.5,light

In [3]:
numeric_df_25 = df_25.select_dtypes(include=["number"]).copy()

if "id_student" in numeric_df_25.columns:
    numeric_df_25 = numeric_df_25.drop(columns=["id_student"])

In [4]:
corr_matrix_25 = numeric_df_25.corr().abs()

In [5]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Heatmap(
        z=corr_matrix_25.values,
        x=corr_matrix_25.columns,
        y=corr_matrix_25.columns,
        colorscale="RdBu",
        zmin=-1,
        zmax=1
    )
)

fig.update_layout(
    title="Correlation Heatmap - First 25%",
    width=1000,
    height=900
)

fig.show()

In [6]:
manual_drop_25 = [
    "max_score_until_cutoff",
    "min_score_until_cutoff",
    "studied_credits",
    "total_clicks_until_cutoff"
]

df_25_reduced = df_25.drop(columns=manual_drop_25)

print(df_25.shape)
print(df_25_reduced.shape)

(32480, 46)
(32480, 42)

In [7]:
from pathlib import Path

Path("data/processed").mkdir(
    parents=True,
    exist_ok=True
)   

df_25_reduced.to_csv(
    "data/processed/df_25_reduced.csv",
    index=False
)

print("df_25_reduced saved successfully.")

df_25_reduced saved successfully.