In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

student_features_first_50 = pd.read_csv("data/processed/student_features_first_50.csv"
)
student_features_first_50

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,subpage,url,avg_score_until_cutoff,min_score_until_cutoff,max_score_until_cutoff,submitted_assessments_until_cutoff,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,27.0,2.0,81.000000,78.0,85.0,3.0,0.0,-1.333333,2.00,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,75.0,43.0,69.333333,68.0,70.0,3.0,2.0,1.666667,0.50,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,22.0,4.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.50,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,105.0,61.0,72.333333,71.0,74.0,3.0,0.0,-2.333333,0.50,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,42.0,8.0,54.000000,30.0,69.0,3.0,3.0,11.666667,0.50,light
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32475,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,...,9.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.25,light
32476,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,...,24.0,0.0,87.000000,80.0,100.0,3.0,1.0,-38.000000,0.25,light
32477,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,...,17.0,0.0,65.000000,60.0,75.0,4.0,0.0,-66.000000,0.25,light
32478,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,...,12.0,0.0,91.500000,83.0,100.0,2.0,0.0,-79.500000,0.25,light
32479,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,...,25.0,0.0,86.666667,80.0,100.0,3.0,0.0,-63.333333,0.25,light

In [2]:
df_50 = student_features_first_50.copy()

print(df_50.shape)

df_50.head()

(32480, 46)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,subpage,url,avg_score_until_cutoff,min_score_until_cutoff,max_score_until_cutoff,submitted_assessments_until_cutoff,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,27.0,2.0,81.000000,78.0,85.0,3.0,0.0,-1.333333,2.0,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,75.0,43.0,69.333333,68.0,70.0,3.0,2.0,1.666667,0.5,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,22.0,4.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.5,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,105.0,61.0,72.333333,71.0,74.0,3.0,0.0,-2.333333,0.5,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,42.0,8.0,54.000000,30.0,69.0,3.0,3.0,11.666667,0.5,light

In [3]:
numeric_df_50 = df_50.select_dtypes(include=["number"]).copy()

if "id_student" in numeric_df_50.columns:
    numeric_df_50 = numeric_df_50.drop(columns=["id_student"])

In [4]:
corr_matrix_50 = numeric_df_50.corr().abs()

In [5]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Heatmap(
        z=corr_matrix_50.values,
        x=corr_matrix_50.columns,
        y=corr_matrix_50.columns,
        colorscale="RdBu",
        zmin=-1,
        zmax=1
    )
)

fig.update_layout(
    title="Correlation Heatmap - First 50%",
    width=1000,
    height=900
)

fig.show()

In [6]:
manual_drop_50 = [
    "max_score_until_cutoff",
    "min_score_until_cutoff",
    "studied_credits",
    "total_clicks_until_cutoff"
]

df_50_reduced = df_50.drop(columns=manual_drop_50)

print(df_50.shape)
print(df_50_reduced.shape)

(32480, 46)
(32480, 42)

In [7]:
from pathlib import Path

Path("data/processed").mkdir(
    parents=True,
    exist_ok=True
)

df_50_reduced.to_csv(
    "data/processed/df_50_reduced.csv",
    index=False
)

print("df_50_reduced saved successfully.")

df_50_reduced saved successfully.