In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

student_features_first_50 = pd.read_csv("C:\\Users\\Ahmed\\Documents\\GazaSkyGeeksOlmpics\\project\\tests\\Fares\\data\\processed\\student_features_first_50.csv"
)
student_features_first_50

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,avg_assessment_relative_time_until_cutoff,avg_submitted_relative_time_until_cutoff,avg_assessment_arab_day_until_cutoff,avg_submitted_arab_day_until_cutoff,avg_submission_delay_relative_until_cutoff,avg_submission_delay_arab_days_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,0.0,-1.333333,0.236318,0.231343,35.447761,34.701493,-0.004975,-0.746269,2.00,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,2.0,1.666667,0.236318,0.242537,35.447761,36.380597,0.006219,0.932836,0.50,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.50,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,0.0,-2.333333,0.236318,0.227612,35.447761,34.141791,-0.008706,-1.305970,0.50,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,3.0,11.666667,0.236318,0.279851,35.447761,41.977612,0.043532,6.529851,0.50,light
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32475,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.25,light
32476,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,...,1.0,-38.000000,0.513011,0.371747,76.951673,55.762082,-0.141264,-21.189591,0.25,light
32477,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,...,0.0,-66.000000,0.597584,0.352230,89.637546,52.834572,-0.245353,-36.802974,0.25,light
32478,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,...,0.0,-79.500000,0.539033,0.243494,80.855019,36.524164,-0.295539,-44.330855,0.25,light
32479,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,...,0.0,-63.333333,0.513011,0.277571,76.951673,41.635688,-0.235440,-35.315985,0.25,light

In [2]:
student_features_first_50 = student_features_first_50.copy()

print(student_features_first_50.shape)

student_features_first_50.head()

(32480, 55)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,late_submissions_until_cutoff,avg_submission_delay_until_cutoff,avg_assessment_relative_time_until_cutoff,avg_submitted_relative_time_until_cutoff,avg_assessment_arab_day_until_cutoff,avg_submitted_arab_day_until_cutoff,avg_submission_delay_relative_until_cutoff,avg_submission_delay_arab_days_until_cutoff,workload_ratio,workload_level
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,0.0,-1.333333,0.236318,0.231343,35.447761,34.701493,-0.004975,-0.746269,2.0,very_high
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,2.0,1.666667,0.236318,0.242537,35.447761,36.380597,0.006219,0.932836,0.5,light
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.5,light
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,0.0,-2.333333,0.236318,0.227612,35.447761,34.141791,-0.008706,-1.305970,0.5,light
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,3.0,11.666667,0.236318,0.279851,35.447761,41.977612,0.043532,6.529851,0.5,light

In [3]:
numeric_df_50 = student_features_first_50.select_dtypes(include=["number"]).copy()

if "id_student" in numeric_df_50.columns:
    numeric_df_50 = numeric_df_50.drop(columns=["id_student"])

In [4]:
corr_matrix_50 = numeric_df_50.corr().abs()

In [5]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Heatmap(
        z=corr_matrix_50.values,
        x=corr_matrix_50.columns,
        y=corr_matrix_50.columns,
        colorscale="RdBu",
        zmin=-1,
        zmax=1
    )
)

fig.update_layout(
    title="Correlation Heatmap - First 50%",
    width=1000,
    height=900
)

fig.show()

In [6]:
manual_drop_50 = [
    "max_score_until_cutoff",
    "min_score_until_cutoff",
    "studied_credits",
    "total_clicks_until_cutoff"
]

student_features_first_50 = student_features_first_50.drop(columns=manual_drop_50)

print(student_features_first_50.shape)

(32480, 51)

In [7]:
from pathlib import Path

Path("data/processed").mkdir(
    parents=True,
    exist_ok=True
)

student_features_first_50.to_csv(
    "data/processed/student_features_first_50.csv",
    index=False
)

print("student_features_first_50 saved successfully.")

student_features_first_50 saved successfully.

#### Now after saving the file of Q2 wth 42 columns ,We'll choose (15) features for now and save it to
#### csv file named **Selected_features_Q2.csv**

In [8]:
# Here we select the features that we will use in our model based on the correlation analysis and domain knowledge.
selected_features = [
    "avg_score_until_cutoff",
    "submitted_assessments_until_cutoff",
    "arab_active_days_equivalent_until_cutoff",
    "avg_submission_delay_arab_days_until_cutoff",
    "homepage",
    "forumng",
    "unique_sites_until_cutoff",
    "unique_activity_types_until_cutoff",
    "clicks_per_active_day_until_cutoff",
    "resource",
    "subpage",
    "url",
    "oucontent",
    "quiz",
    "highest_education"
]


selected_df = student_features_first_50[selected_features + ["target"]]

selected_df.to_csv(
    "C:\\Users\\Ahmed\\Documents\\GazaSkyGeeksOlmpics\\project\\tests\\Fares\\data\\processed\\Selected_features_Q2.csv",
    index=False
)